apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: librarian
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: 3
    spec:
      serviceAccountName: librarian-service-account@shikanime-studio-labs.iam.gserviceaccount.com
      containers:
        - image: gcr.io/shikanime-studio-labs/librarian
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: shikanime-studio-labs
            - name: VERTEXAI_SEARCH_LOCATION_ID
              value: global
            - name: VERTEXAI_SEARCH_DATA_STORE_ID
              value: scientific_1704814637510
